# Generated by Django 4.0.2 on 2022-02-27 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='collections',
            name='bookmarks',
            field=models.ManyToManyField(to='reviews.Movie'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
