# Generated by Django 4.0.2 on 2022-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_collections_movie_remove_movie_bookmarked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='bookmarks',
            field=models.ManyToManyField(null=True, to='reviews.Movie'),
        ),
    ]
