# Generated by Django 4.0.2 on 2022-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_collections_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='reviews.Movie'),
        ),
    ]
