# Generated by Django 4.0.2 on 2022-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_collections_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='movie',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='reviews.Collections'),
        ),
    ]
