# Generated by Django 4.0.2 on 2022-02-27 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_remove_collections_bookmarks_movie_folders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collections',
            unique_together={('name', 'user')},
        ),
    ]
