# Generated by Django 4.0.2 on 2022-02-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_movie_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.collections')),
            ],
        ),
        # CHANGE
        migrations.RemoveField(
            model_name='movie',
            name='folders',
        ),
        migrations.AddField(
            model_name='movie',
            name='folders',
            field=models.ManyToManyField(blank=True, through='reviews.Bookmark', to='reviews.Collections'),
        ),
        #----
        migrations.AddField(
            model_name='bookmark',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='reviews.movie'),
        ),
    ]
